name: astro_tak
description: India Today Assignment Project

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  flutter_gen: ^4.1.5
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  http: ^0.13.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  flutter_gen_runner: ^4.1.5



flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80   # Optional (default: 80)

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true

  assets:
    enabled: true
    package_parameter_enabled: false
    # Assets.imagesChip
    # style: camel-case

    # Assets.images_chip
    # style: snake-case

    # Assets.images.chip (default style)
    # style: dot-delimiter

  fonts:
    enabled: true

flutter:

  uses-material-design: true

  assets:
    - assets/images/


